version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-tracker
    restart: unless-stopped
    volumes:
      - tracker-data:/data
    environment:
      - TOKEN=your_bot_token
      - OWNER_ID=your_owner_id
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

volumes:
  tracker-data:
